safemail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spam_detection.urls')),
]

spam_detection/urls.py
from django.urls import path
from . import views

app_name = 'spam_detection'

#Determine URL patterns for all the views.
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('check-spam/', views.check_spam, name='check_spam'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('blacklist/', views.blacklist, name='blacklist'),
    path('whitelist/', views.whitelist, name='whitelist'),
    path('metrics/', views.evaluation_metrics, name='metrics'),
]

spam_detection/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#User Model
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    blacklisted_senders = models.ManyToManyField('BlacklistedSender', blank=True)
    whitelisted_senders = models.ManyToManyField('WhitelistedSender', blank=True)

#Blacklist Model
class BlacklistedSender(models.Model):
    email = models.EmailField(unique=True)

#Whitelist Model
class WhitelistedSender(models.Model):
    email = models.EmailField(unique=True)

spam_detection/forms.py
from django import forms


class EmailCheckForm(forms.Form):
    sender_email = forms.EmailField(label='Sender Email')
    email_text = forms.CharField(label='Email Text', widget=forms.Textarea)

spam_detection/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, BlacklistedSender, WhitelistedSender
from .forms import EmailCheckForm
from .naive_bayes import NaiveBayesClassifier
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
import json

import nltk
from nltk.corpus import stopwords
import csv

# Create your views here.

#Default view - The one that loads when you open the website
def index(request):
    if request.user.is_authenticated:
        #Get the current user
        user_profile = UserProfile.objects.get(user=request.user)
        #Count no. of spam emails checked
        spam_count = user_profile.blacklisted_senders.count()
        #Count no. of ham emails checked
        not_spam_count = user_profile.whitelisted_senders.count()
        total = spam_count + not_spam_count
        context = {
            'spam_count': spam_count,
            'not_spam_count': not_spam_count,
            'total_mail': total,
        }
        return render(request, 'spam_detection/dashboard.html', context)
    else:
        return redirect('spam_detection:login')
    
#View to show evaluation metrics like accuracy, precision and recall
def evaluation_metrics(request):
    return render(request, 'spam_detection/metrics.html')
    

#View to register a new user
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('spam_detection:login')
    else:
        form = UserCreationForm()
    return render(request, 'spam_detection/register.html', {'form': form})

#View to login a user
def user_login(request):
    #Handle Post Requests
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('spam_detection:dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'spam_detection/login.html', {'form': form})

#View to logout a user
def user_logout(request):
    logout(request)
    return redirect('spam_detection:login')


#View to render a dashboard
@login_required
def dashboard(request):
    username = request.user.username

    user_profile = UserProfile.objects.get(user=request.user)

    spam_count = user_profile.blacklisted_senders.count()
    not_spam_count = user_profile.whitelisted_senders.count()
    total = spam_count + not_spam_count
    context = {
        'username': username,
        'spam_count': spam_count,
        'not_spam_count': not_spam_count,
        'total_mail': total
    }
    return render(request, 'spam_detection/dashboard.html', context)



english_stopwords = stopwords.words('english')

emails = []
labels = []

def read_csv(file_path):
    emails = []
    labels = []
    with open(file_path, 'r', newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            labels.append(1 if row['Category'] == 'spam' else 0)
            emails.append(row['Message'])
    return emails, labels

emails, labels = read_csv('./phisingmail.csv')

classifier = NaiveBayesClassifier()
classifier.train(emails, labels)

@login_required
def check_spam(request):
    if request.method == 'POST':
        form = EmailCheckForm(request.POST)
        if form.is_valid():
            sender_email = form.cleaned_data['sender_email']
            email_text = form.cleaned_data['email_text']
            user_profile = UserProfile.objects.get(user=request.user)

            #Check if sender is blacklisted
            blacklisted = user_profile.blacklisted_senders.filter(email=sender_email)
            if blacklisted.exists():
                warning = "This email address is already blacklisted."
                form = EmailCheckForm()
                context = {
                    'warning': warning,
                    'form': form,
                }
                return render(request, 'spam_detection/check_spam.html', context)
            is_spam, log_prob_diff, confidence, features, matching_words  = classifier.predict(email_text)
            print(is_spam)
            
            
            if is_spam is True:
                blacklisted_sender, _ = BlacklistedSender.objects.get_or_create(email=sender_email)
                user_profile.blacklisted_senders.add(blacklisted_sender)
                context = {
                    'is_spam': is_spam,
                    'sender_email': sender_email,
                    'log_prob_diff': log_prob_diff,
                    'confidence': confidence,
                    'features': features,
                    'matching_words': matching_words,
                }
                return render(request, 'spam_detection/spam_result.html', context)
            if is_spam is False:
                whitelisted_sender, _ = WhitelistedSender.objects.get_or_create(email=sender_email)
                user_profile.whitelisted_senders.add(whitelisted_sender)
                context = {
                    'is_spam': is_spam,
                    'sender_email': sender_email,
                    'log_prob_diff': log_prob_diff,
                    'confidence': confidence,
                    'features': features,
                    'matching_words': matching_words,
                }
                return render(request, 'spam_detection/not_spam_result.html', context)
    else:
        form = EmailCheckForm()
    return render(request, 'spam_detection/check_spam.html', {'form': form})

@login_required
def blacklist(request):
    if request.user.is_authenticated:

        user_profile = UserProfile.objects.get(user=request.user)

        blacklisted_users = user_profile.blacklisted_senders.all()
        username = request.user.username
        context = {
            'username': username,
            'blacklist': blacklisted_users,
        }
        return render(request, 'spam_detection/blacklist.html', context)
    
@login_required
def whitelist(request):
    if request.user.is_authenticated:
        user_profile = UserProfile.objects.get(user=request.user)
        whitelisted_users = user_profile.whitelisted_senders.all()
        username = request.user.username
        context = {
            'username': username,
            'whitelist': whitelisted_users,
        }
        return render(request, 'spam_detection/whitelist.html', context)

spam_detection/templates/spam_detection/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SafeMail{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <!--<header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'spam_detection:dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'spam_detection:logout' %}">Logout</a></li>
                <li><a href="{% url 'spam_detection:blacklist' %}">Blacklist</a></li>
                <li><a href="{% url 'spam_detection:whitelist' %}">Whitelist</a></li>
                
                {% else %}

                {% endif %}
            </ul>
        </nav>
    </header>-->

    <main>
        {% block content %}
        {% endblock %}
    </main>
    {% block scripts %}
    {% endblock %}
</body>
</html>

spam_detection/templates/spam_detection/blacklist.html
<!-- spam_detector/templates/spam_detector/spam_result.html -->
{% extends 'spam_detection/base.html' %}
{% load static %}

{% block content %}

<header class="header-no-list">
  <ul class="nav-list">
    <li><a href="{% url 'spam_detection:dashboard' %}">Dashboard</a></li>
    <li><a href="{% url 'spam_detection:check_spam' %}">Check Spam</a></li>
    <li><a href="{% url 'spam_detection:whitelist' %}">Whitelist</a></li>
  </ul>
  <img src="{% static '/img/whitesolologo.png' %}" alt="">
  <a href="{% url 'spam_detection:logout' %}" class="logout">Logout</a>
</header>


  <h2 style="text-align: center; margin-top: 50px;">{{ username }}'s Blacklist</h2>
  <div class="table-container">
    <table class="list-table">
      <tr>
        <th>S.No.</th>
        <th>Email Sender Address</th>
      </tr>
      {% for users in blacklist %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ users.email }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  
{% endblock %}

spam_detection/templates/spam_detection/check_spam.html
<!-- spam_detector/templates/spam_detector/check_spam.html -->
{% extends 'spam_detection/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

  <header class="header-no-list">
    <ul class="nav-list">
      <li><a href="{% url 'spam_detection:dashboard' %}">Dashboard</a></li>
      <li><a href="{% url 'spam_detection:whitelist' %}">Whitelist</a></li>
      <li><a href="{% url 'spam_detection:blacklist' %}">Blacklist</a></li>
    </ul>
    <img src="{% static '/img/whitesolologo.png' %}" alt="">
    <a href="{% url 'spam_detection:logout' %}" class="logout">Logout</a>
  </header>


  <div class="spam-form">
    <form method="post">
      {% csrf_token %}
      <div class="form-flex">
        {{ form|crispy }}
        <div class="button-container">
          <button type="submit">Check</button>
        </div>
        <p class="reminder" style="padding: 3px; background-color: red; color: white; border-radius: 5px;">{{ warning }}</p>
      </div>
    </form>
  </div>
{% endblock %}

spam_detection/templates/spam_detection/dashboard.html
{% extends 'spam_detection/base.html' %}
{% load static %}

{% block content %}

  <header class="header-no-list">
    <img src="{% static '/img/whitesolologo.png' %}" alt="">
    <a href="{% url 'spam_detection:logout' %}" class="logout">Logout</a>
  </header>


  <section id="main-dashboard">
    <h1>Hi, {{ username }}</h1>
    <div id="user-stats">
      <div class="stats">
        <h3>Keeping Your Inbox Safe</h3>
        <p>How the system works?</p>
        <ul>
          <li><strong>Data Preprocessing</strong><br>Emails are cleaned by removing symbols and stopwords.</li>
          <li><strong>Training Phase</strong><br>System is trained on a dataset of pre-labeled emails.</li>
          <li><strong>Classification</strong><br>The sytem analyzes words in the email and calculates probability of it belonging to the spam or non-spam category.</li>
          <li><strong>Spam Prediction</strong><br>Based on probabilites, the system predicts if the email is spam or not, along with the confidence score (high, medium, low)</li>
        </ul>
        <!--<p>Spam emails: {{ spam_count }}</p>
        <p>Not spam emails: {{ not_spam_count }}</p>
        <p>Total mails checked: {{ total_mail }}</p>-->
      </div>
      <div class="pie-chart">
        <div>
          <canvas id="myPieChart"></canvas>
        </div>
      </div>
      <div class="navbar">
        <!--<ul>
          <li><a href="{% url 'spam_detection:check_spam' %}">Check Spam</a></li>
          <li><a href="{% url 'spam_detection:blacklist' %}">Blacklist</a></li>
          <li><a href="{% url 'spam_detection:whitelist' %}">Whitelist</a></li>
        </ul>-->
        <a href="{% url 'spam_detection:check_spam' %}">Check Spam</a>
        <a href="{% url 'spam_detection:blacklist' %}">Blacklist</a>
        <a href="{% url 'spam_detection:whitelist' %}">Whitelist</a>
        <a href="{% url 'spam_detection:metrics' %}">Evaluation Metrics</a>
      </div>
    </div>
  </section>

  <div id="spam-count" style="display: none;">{{ spam_count }}</div>
  <div id="not-spam-count" style="display: none;">{{ not_spam_count }}</div>

{% endblock %}

{% load static %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    var spamCount = document.getElementById('spam-count').innerHTML;
    var notSpamCount = document.getElementById('not-spam-count').innerHTML;
    console.log(spamCount, notSpamCount)
    var ctx = document.getElementById('myPieChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: ['Spam Emails', 'Ham Emails'],
            datasets: [{
                data: [spamCount, notSpamCount],
                backgroundColor: ['#877878', '#788778'],
            }]
        }
    });
</script>
{% endblock %}

spam_detection/templates/spam_detection/index.html
{% extends 'spam_detection/base.html' %}

{% block content %}
<h1>Hello</h1>
{% endblock %}

spam_detection/templates/spam_detection/login.html
{% extends 'spam_detection/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}

<!--<img src="login/img/logofull.png" alt="">-->
<div id="logo-single">
  <img src="{% static '/img/logofull.png' %}" alt="">
</div>


<div class="login_form">
  <form method="post">
    {% csrf_token %}
    <div class="form-flex">
      {{ form|crispy }}
      <div class="button-container">
        <button type="submit">Login</button>
      </div>
      <p class="reminder">Not registered yet? <a href="{% url 'spam_detection:register' %}">Sign Up</a></p>
    </div>
  </form>
</div>

{% endblock %}

spam_detection/templates/spam_detection/metrics.html
{% extends 'spam_detection/base.html' %}
{% load static %}

{% block content %}

<header class="header-no-list">
    <ul class="nav-list">
      <li><a href="{% url 'spam_detection:dashboard' %}">Dashboard</a></li>
      <li><a href="{% url 'spam_detection:check_spam' %}">Check Spam</a></li>
      <li><a href="{% url 'spam_detection:blacklist' %}">Blacklist</a></li>
      <li><a href="{% url 'spam_detection:whitelist' %}">Whitelist</a></li>
    </ul>
    <img src="{% static '/img/whitesolologo.png' %}" alt="">
    <a href="{% url 'spam_detection:logout' %}" class="logout">Logout</a>
  </header>

  <section id="main-dashboard">
    <h1 style="text-align: center;">Evaluation Metrics</h1>
    <hr style="width: 95%">
    <div id="metric-stats">
      <div class="accuracy">
        <h4 style="text-align: center; font-weight: 400;">Accuracy</h4>
        <h3 style="text-align: center;">95.58%</h3>
        <div>
            <canvas id="accuracyChart"></canvas>
        </div>
        <p style="padding: 5px; text-align: justify;">The classifier correctly predicted the category (spam or ham) for 93.05% of the emails in the test set.</p>
      </div>
      <div class="precision">
        <h4 style="text-align: center; font-weight: 400;">Precision</h4>
        <h3 style="text-align: center;">89.19%</h3>
        <div>
            <canvas id="precisionChart"></canvas>
        </div>
        <p style="padding: 5px; text-align: justify;">Of the total emails that the classifier predicted as spam, 89.19% were actually spam.</p>
      </div>
      <div class="recall">
        <h4 style="text-align: center; font-weight: 400;">Recall</h4>
        <h3 style="text-align: center;">98.28%</h3>
        <div>
            <canvas id="recallChart"></canvas>
        </div>
        <p style="padding: 5px; text-align: justify;">The classifier correctly identified 98.28% of all the actual spam emails in the test set.</p>

      </div>
      <div class="fonescore">
        <h4 style="text-align: center; font-weight: 400;">F1 Score</h4>
        <h3 style="text-align: center;">93.52%</h3>
        <div>
            <canvas id="foneChart"></canvas>
        </div>
        <p style="padding: 5px; text-align: justify;">The F1 score provides a balanced measure of the classifier's performance, considering both precision and recall. A score of 93.52% indicates a good balance between correctly identifying spam emails and avoiding false positives.</p>

      </div>
    </div>

{% endblock %}

{% block scripts %}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    var ctx1 = document.getElementById('accuracyChart').getContext('2d');
    var ctx2 = document.getElementById('precisionChart').getContext('2d');
    var ctx3 = document.getElementById('recallChart').getContext('2d');
    var ctx4 = document.getElementById('foneChart').getContext('2d');

    var myChart1 = new Chart(ctx1, {
        type: 'pie',
        data: {
            labels: [],
            datasets: [{
                data: [95.58, 4.42],
                backgroundColor: ['#567568', '#C9B1BD']
            }]
        }
    });

    var myChart2 = new Chart(ctx2, {
        type: 'pie',
        data: {
            labels: [],
            datasets: [{
                data: [89.19, 10.81],
                backgroundColor: ['#56445D', '#8FBC94']
            }]
        }
    });

    var myChart3 = new Chart(ctx3, {
        type: 'pie',
        data: {
            labels: [],
            datasets: [{
                data: [98.28, 1.72],
                backgroundColor: ['#222E50', '#B5CA8D']
            }]
        }
    });

    var myChart4 = new Chart(ctx4, {
        type: 'pie',
        data: {
            labels: [],
            datasets: [{
                data: [93.52, 6.48],
                backgroundColor: ['#392F5A', '#A8C7BB']
            }]
        }
    });
</script>



{% endblock %}

spam_detection/templates/spam_detection/not_spam_result.html
<!-- spam_detector/templates/spam_detector/not_spam_result.html -->
{% extends 'spam_detection/base.html' %}
{% load static %}

{% block content %}

<header class="header-no-list">
  <ul class="nav-list">
    <li><a href="{% url 'spam_detection:dashboard' %}">Dashboard</a></li>
    <li><a href="{% url 'spam_detection:check_spam' %}">Check Spam</a></li>
    <li><a href="{% url 'spam_detection:blacklist' %}">Blacklist</a></li>
    <li><a href="{% url 'spam_detection:whitelist' %}">Whitelist</a></li>
  </ul>
  <img src="{% static '/img/whitesolologo.png' %}" alt="">
  <a href="{% url 'spam_detection:logout' %}" class="logout">Logout</a>
</header>

<div class="show-email">
  <p>This email from <strong>{{ sender_email }}</strong> is a:</p>
</div>
<div class="spam-image">
  <img src="{% static '/img/hamalert.png' %}" alt="spam image" />
</div>
<div class="sender-warning">
  <p>This sender has been added to your <strong>WHITELIST</strong>.</p>
</div>
<hr style="width: 90%">
<div class="main-result-container">
  <div class="metrics">
    <!--<p style="text-decoration: underline; text-align: center;">Metrics</p>-->
    <p style="margin-left: 17px; height: auto">
      Logarithmic Probability Difference:
    </p>
    <p style="margin-left: 17px; height: auto"><b>{{ log_prob_diff }}</b></p>
    <p style="margin: 50px 0 0 17px">Confidence:</p>
    <p style="margin-left: 17px"><b>{{ confidence }}</b></p>
  </div>
  <div class="indicative-features">
    <p style="text-decoration: underline; text-align: center;">Indicative Features</p>
    <table>
      <tr>
        <th>Word</th>
        <th>Count</th>
      </tr>
      {% for word, count in features %}
      <tr>
        <td>{{ word }}</td>
        <td>{{ count }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div class="matching-words">
    <p style="text-decoration: underline; text-align: center;">Matching Words</p>
    <table>
      <tr>
        <th>Words</th>
      </tr>
      {% for words in matching_words %}
      <tr>
        <td>{{ words }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
    
</div>
{% endblock %}

spam_detection/templates/spam_detection/register.html
<!-- spam_detector/templates/spam_detector/register.html -->
{% extends 'spam_detection/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div id="logo-single">
  <img src="{% static '/img/logofull.png' %}" alt="">
</div>


<div class="register-form">
  <form method="post">
    {% csrf_token %}
    <div class="form-flex">
      {{ form|crispy }}
      <div class="button-containter">
        <button type="submit">Register</button>
      </div>
      <p class="reminder">Already registered? <a href="{% url 'spam_detection:login' %}">Login</a></p>
    </div>
  </form>
</div>

  
{% endblock %}

spam_detection/templates/spam_detection/spam_result.html
<!-- spam_detector/templates/spam_detector/spam_result.html -->
{% extends 'spam_detection/base.html' %}
{% load static %}

{% block content %}



<header class="header-no-list">
  <ul class="nav-list">
    <li><a href="{% url 'spam_detection:dashboard' %}">Dashboard</a></li>
    <li><a href="{% url 'spam_detection:check_spam' %}">Check Spam</a></li>
    <li><a href="{% url 'spam_detection:blacklist' %}">Blacklist</a></li>
    <li><a href="{% url 'spam_detection:whitelist' %}">Whitelist</a></li>
  </ul>
  <img src="{% static '/img/whitesolologo.png' %}" alt="">
  <a href="{% url 'spam_detection:logout' %}" class="logout">Logout</a>
</header>


<div class="show-email">
  <p>This email from <strong>{{ sender_email }}</strong> is a:</p>
</div>
<div class="spam-image">
  <img src="{% static '/img/spamalert.png' %}" alt="spam image" />
</div>
<div class="sender-warning">
  <p>This sender has been added to your <strong>BLACKLIST</strong>.</p>
</div>
<hr style="width: 90%">
<div class="main-result-container">
  <div class="metrics">
    <!--<p style="text-decoration: underline; text-align: center;">Metrics</p>-->
    <p style="margin-left: 17px; height: auto">
      Logarithmic Probability Difference:
    </p>
    <p style="margin-left: 17px; height: auto"><b>{{ log_prob_diff }}</b></p>
    <p style="margin: 50px 0 0 17px">Confidence:</p>
    <p style="margin-left: 17px"><b>{{ confidence }}</b></p>
  </div>
  <div class="indicative-features">
    <p style="text-decoration: underline; text-align: center;">Indicative Features</p>
    <table>
      <tr>
        <th>Word</th>
        <th>Count</th>
      </tr>
      {% for word, count in features %}
      <tr>
        <td>{{ word }}</td>
        <td>{{ count }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div class="matching-words">
    <p style="text-decoration: underline; text-align: center;">Matching Words</p>
    <table>
      <tr>
        <th>Words</th>
      </tr>
      {% for words in matching_words %}
      <tr>
        <td>{{ words }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
    
</div>


  
{% endblock %}

spam_detection/templates/spam_detection/whitelist.html
<!-- spam_detector/templates/spam_detector/spam_result.html -->
{% extends 'spam_detection/base.html' %}
{% load static %}

{% block content %}

<header class="header-no-list">
  <ul class="nav-list">
    <li><a href="{% url 'spam_detection:dashboard' %}">Dashboard</a></li>
    <li><a href="{% url 'spam_detection:check_spam' %}">Check Spam</a></li>
    <li><a href="{% url 'spam_detection:blacklist' %}">Blacklist</a></li>
  </ul>
  <img src="{% static '/img/whitesolologo.png' %}" alt="">
  <a href="{% url 'spam_detection:logout' %}" class="logout">Logout</a>
</header>


  <h2 style="text-align: center; margin-top: 50px;">{{ username }}'s Whitelist</h2>
  <div class="table-container">
    <table class="list-table">
      <tr>
        <th>S.No.</th>
        <th>Email Sender Address</th>
      </tr>
      {% for users in whitelist %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ users.email }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>

  
  
{% endblock %}